### ISSUE TITLE
rekall / volatility error

### ISSUE THREAD

**Issue by yguseto** [libvmi/python#36]
I want to connect machine with rekall but i got these errors

```

Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/usr/local/lib/python3.6/dist-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/usr/local/lib/python3.6/dist-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/guess_profile.py", line 737, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi://xen/win7.


```

**Comment by Wenzel** [comment]
You should look for a similar issue on https://github.com/google/rekall/issues, or open one.

**Comment by yguseto** [comment]
@Wenzel but i got similar error with volatility(libvmi ext)

**Comment by Wenzel** [comment]
Use the verbose mode to discover why Rekall/Volatility can't initialize the address space

**Comment by Wenzel** [comment]
So try to understand what is happening, i can't really help you here

**Comment by yguseto** [comment]
:D oky i solved with your blog 
https://wenzel.github.io/2018/04/10/live_memory_forensics_rekall.html 
in first i install rekall directly and save plugin manuel
