### ISSUE TITLE
python libvmi on CentOS 7/8

### ISSUE THREAD

**Issue by 0xarash** [libvmi/python#61]
Hello,
I am trying to setup python binding on CentOS ver. 7 and 8  but receive the error message at the bottom, have anyone tested on CentOS or any idea what is the problem.

I also tested on Ubuntu and it work perfectly, but I need it to work on CentOS too. 

Appreciate any help

```
$ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    'libvmi': ['*_cdef.h']
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options                                                                                      
    ep.load()(self, ep.name, value)
  File "/home/arash/libvmi/python/.eggs/cffi-1.14.0-py3.6-linux-x86_64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules                                                    
    add_cffi_module(dist, cffi_module)
  File "/home/arash/libvmi/python/.eggs/cffi-1.14.0-py3.6-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module                                                  
    execfile(build_file_name, mod_vars)
  File "/home/arash/libvmi/python/.eggs/cffi-1.14.0-py3.6-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile                                                         
    exec(code, glob, glob)
  File "libvmi/libvmi_build.py", line 60, in <module>
    libvmi_libs = get_libs('libvmi')
  File "libvmi/libvmi_build.py", line 37, in get_libs
    libs = pkgconfig.libs(package)
  File "/usr/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 165, in libs
    _raise_if_not_exists(package)
  File "/usr/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists                                                                              
    raise PackageNotFoundError(package)
pkgconfig.pkgconfig.PackageNotFoundError: libvmi not found
```

**Comment by Wenzel** [comment]
The error message is quite clear.
Pkg-config cannot find libvmi library.

**Comment by 0xarash** [comment]
@Wenzel 
Yes it could not find libvmi, but want I have trouble is that what libvmi package?, is there any other libvmi this setup script supposed to find, or I should somehow configure, beside the libvmi library.

**Comment by Wenzel** [comment]
libvmi installs a `libvmi.pc` file, which is a pkg-config file.
you need to learn how pkg-config works and how it finds the libraries on your system.

This is not a libvmi/python issue.

**Comment by Wenzel** [comment]
@0xarash usually adjusting the `PKG_CONFIG_PATH` is what you are looking for:
https://askubuntu.com/a/210235/917540

**Comment by 0xarash** [comment]
@Wenzel It worked. thanks a lot.
